/**
 * 훈민바름 — 음소–자모값 대응 등록부 (표기규격 v2.0, 제19조 ⑨).
 *
 * ⚠ 자동 생성 파일이다. 직접 고치지 말 것.
 *   생성: python3 tools/gen_registry_js.py
 *   원본: hmbr_registry_v2_0.json (문서 별첨 표 11 · 마스터 표 15)
 *
 * 문서와 값이 어긋나면 문서가 정본이다. 여기 실린 부호열은 모두
 * 조합용 자모(U+1100–U+11FF, U+A960–, U+D7B0–)이며 호환용 자모
 * U+3130–U+318F 는 정본에서 배제한다(부호 정책).
 */

export const SPEC_VERSION = "2.0";
export const DOC_BUILD = "v18";
export const MODULE_ID = "EN";
export const JAMO_POLICY = "조합용 자모(U+1100~U+11FF, U+A960~U+A97F, U+D7B0~U+D7FF)만 쓴다. 호환용 자모 U+3130~U+318F는 정본 데이터에서 제외한다.";
export const DISPLAY_NOTE = "정본 부호열과 화면 표시는 분리한다. 가독 표시(예: 핔)는 표시 프로파일의 산물이며 정본 값을 바꾸지 않는다.";

/** 부록 E 의 역변환 규칙. MAJOR 판올림 시 공개 의무(제24조 ③). */
export const REVERSE_RULES = {
  "RV-EN-BASE-00": {
    name: "항등 환원",
    direction: "v2.0 ↔ v1.2",
    lossless: true,
    requires: [],
    mapDown: {},
    note: "v1.2와 v2.0의 부호열이 같은 항목. 변환이 필요 없다.",
  },
  "RV-EN-CLUSTER-01": {
    name: "어말 자음군 종성열의 환원",
    direction: "v2.0 ↔ v1.2",
    lossless: true,
    requires: [],
    mapDown: {},
    note: "v2.0은 어말 자음군을 발음 순서대로 종성 자모열로 적고 원어에 없는 모음을 넣지 않는다. 환원할 때에는 종성열을 그대로 IPA 자음열로 되돌린다.",
  },
  "RV-EN-CODA-01": {
    name: "원어 종성 직접 대응의 환원",
    direction: "v2.0 → v1.2",
    lossless: false,
    requires: ["ipa"],
    mapDown: {"ᆿ": "ᆨ", "ᇀ": "ᆮ", "ᇁ": "ᆸ", "ᆺ": "ᆮ"},
    note: "v2.0은 어말 자음을 원어 IPA에 직접 대응시킨다. v1.2로 내릴 때에는 한국어 말음 중화에 준하여 ᆿ→ᆨ, ᇀ→ᆮ, ᇁ→ᆸ, ᆺ→ᆮ로 사상한다. 이 방향은 다대일이므로 IPA 원문 필드를 함께 보존하여야 복원할 수 있다.",
  },
  "RV-EN-S-01": {
    name: "영어 /s/ 초성 위치형 환원",
    direction: "v2.0 → v1.2",
    lossless: true,
    requires: [],
    mapDown: {"ᄉ": "ᄊ", "ᄊ": "ᄊ"},
    note: "v2.0의 초성 ㅅ(U+1109)과 ㅆ(U+110A)을 모두 음소 /s/로 환원한다. v1.2로 내릴 때에는 두 형태를 모두 ㅆ(U+110A)으로 사상한다. 음소 수준에서 무손실이다.",
  },
};

/**
 * 등록부 항목. 표 15 의 12개 항목을 그대로 옮기되, 자바스크립트에서
 * 다루기 쉬운 이름을 쓴다.
 *   id/jv        음소 ID · 자모값 ID   (EN-P-015 / JV-EN-015)
 *   ipa/bare     IPA 표기 · 구분기호를 뗀 형태
 *   mode         phonemic | phonetic   (이음은 기본 표에서 뺀다)
 *   canonical    정본 부호열
 *   pos          위치별 부호열 (초성 · 종성 · 중성 · 문맥별 초성)
 *   rules        역변환 규칙 식별자
 *   context      문맥 조건 (규범 서술)
 *   status       확정 | 잠정 | 시험 | 시범값 | 미정 …  (참고 항목)
 */
export const ENTRIES = [
  {
    id: "EN-P-001", jv: "JV-EN-001",
    ipa: "/b/", bare: "b",
    mode: "phonemic", canonical: "ᄇ",
    pos: {"초성": "ᄇ", "종성": "ᆸ"},
    rules: ["RV-EN-BASE-00"],
    slug: "EN-b", cls: "순음 파열음", status: "확정",
    context: "",
    example: "boost 부웃ᇀ",
  },
  {
    id: "EN-P-002", jv: "JV-EN-002",
    ipa: "/p/", bare: "p",
    mode: "phonemic", canonical: "ᄑ",
    pos: {"초성": "ᄑ", "종성": "ᇁ"},
    rules: ["RV-EN-CODA-01"],
    slug: "EN-p", cls: "순음 파열음", status: "확정",
    context: "종성은 한국어 말음 중화를 적용하지 않는다(제5조의2 ④).",
    example: "cup 컾",
  },
  {
    id: "EN-P-003", jv: "JV-EN-003",
    ipa: "/m/", bare: "m",
    mode: "phonemic", canonical: "ᄆ",
    pos: {"초성": "ᄆ", "종성": "ᆷ"},
    rules: ["RV-EN-BASE-00"],
    slug: "EN-m", cls: "순음 비음", status: "확정",
    context: "",
    example: "moon 무운",
  },
  {
    id: "EN-P-004", jv: "JV-EN-004",
    ipa: "/v/", bare: "v",
    mode: "phonemic", canonical: "ᅄ",
    pos: {"초성": "ᅄ", "종성": "ᇦ"},
    rules: ["RV-EN-BASE-00"],
    slug: "EN-v", cls: "순치 마찰음", status: "잠정",
    context: "종성형은 등록 연서형을 위치형으로 시험한다.",
    example: "very",
  },
  {
    id: "EN-P-005", jv: "JV-EN-005",
    ipa: "/f/", bare: "f",
    mode: "phonemic", canonical: "ᅋ",
    pos: {"초성": "ᅋ", "종성": "ᇴ"},
    rules: ["RV-EN-BASE-00"],
    slug: "EN-f", cls: "순치 마찰음", status: "잠정",
    context: "종성형은 등록 연서형을 위치형으로 시험한다.",
    example: "friend",
  },
  {
    id: "EN-P-006", jv: "JV-EN-006",
    ipa: "/w/", bare: "w",
    mode: "phonemic", canonical: "ᅇ",
    pos: {"초성": "ᅇ", "종성": "ᇮ"},
    rules: ["RV-EN-BASE-00"],
    slug: "EN-w", cls: "순-연구개 접근음", status: "시험",
    context: "종성형은 언어모듈에서 별도 검증한다.",
    example: "wood",
  },
  {
    id: "EN-P-007", jv: "JV-EN-007",
    ipa: "/d/", bare: "d",
    mode: "phonemic", canonical: "ᄃ",
    pos: {"초성": "ᄃ", "종성": "ᆮ"},
    rules: ["RV-EN-BASE-00"],
    slug: "EN-d", cls: "치경 파열음", status: "확정",
    context: "",
    example: "good 굳",
  },
  {
    id: "EN-P-008", jv: "JV-EN-008",
    ipa: "/t/", bare: "t",
    mode: "phonemic", canonical: "ᄐ",
    pos: {"초성": "ᄐ", "종성": "ᇀ"},
    rules: ["RV-EN-CODA-01"],
    slug: "EN-t", cls: "치경 파열음", status: "확정",
    context: "종성은 한국어 말음 중화를 적용하지 않는다(제5조의2 ④).",
    example: "soot 숱",
  },
  {
    id: "EN-P-009", jv: "JV-EN-009",
    ipa: "/n/", bare: "n",
    mode: "phonemic", canonical: "ᄂ",
    pos: {"초성": "ᄂ", "종성": "ᆫ"},
    rules: ["RV-EN-BASE-00"],
    slug: "EN-n", cls: "치경 비음", status: "확정",
    context: "",
    example: "sun 썬",
  },
  {
    id: "EN-P-010", jv: "JV-EN-010",
    ipa: "/g/", bare: "g",
    mode: "phonemic", canonical: "ᄀ",
    pos: {"초성": "ᄀ", "종성": "ᆨ"},
    rules: ["RV-EN-BASE-00"],
    slug: "EN-g", cls: "연구개 파열음", status: "확정",
    context: "",
    example: "dog ᄃᆂᆨ",
  },
  {
    id: "EN-P-011", jv: "JV-EN-011",
    ipa: "/k/", bare: "k",
    mode: "phonemic", canonical: "ᄏ",
    pos: {"초성": "ᄏ", "종성": "ᆿ"},
    rules: ["RV-EN-CODA-01"],
    slug: "EN-k", cls: "연구개 파열음", status: "확정",
    context: "종성은 한국어 말음 중화를 적용하지 않는다(제5조의2 ④).",
    example: "pick 정본 ᄑᆝᆿ · 가독 표시 핔",
  },
  {
    id: "EN-P-012", jv: "JV-EN-012",
    ipa: "/ŋ/", bare: "ŋ",
    mode: "phonemic", canonical: "ᆼ",
    pos: {"종성": "ᆼ"},
    rules: ["RV-EN-BASE-00"],
    slug: "EN-ng", cls: "연구개 비음", status: "확정",
    context: "영어에서 어두에 오지 않는다.",
    example: "sing ᄊᆝᆼ",
  },
  {
    id: "EN-P-013", jv: "JV-EN-013",
    ipa: "/θ/", bare: "θ",
    mode: "phonemic", canonical: "ᅅ",
    pos: {"초성": "ᅅ"},
    rules: ["RV-EN-BASE-00"],
    slug: "EN-theta", cls: "치 마찰음", status: "종성 미정",
    context: "종성 부호열은 미정(제5조의2 ⑥).",
    example: "thank ᅅᅢᆼᆿ",
  },
  {
    id: "EN-P-014", jv: "JV-EN-014",
    ipa: "/ð/", bare: "ð",
    mode: "phonemic", canonical: "ᅂ",
    pos: {"초성": "ᅂ"},
    rules: ["RV-EN-BASE-00"],
    slug: "EN-eth", cls: "치 마찰음", status: "종성 미정",
    context: "종성 부호열은 미정(제5조의2 ⑥).",
    example: "they ᅂᅦ이",
  },
  {
    id: "EN-P-015", jv: "JV-EN-015",
    ipa: "/s/", bare: "s",
    mode: "phonemic", canonical: "ᄊ",
    pos: {"초성_기타모음앞": "ᄊ", "초성_고원순모음앞": "ᄉ", "초성_자음앞": "ᄉᅠ", "종성": "ᆺ"},
    rules: ["RV-EN-S-01", "RV-EN-CODA-01"],
    slug: "EN-s", cls: "치경 마찰음", status: "초성 위치형 시범 · 종성 확정",
    context: "/uː, ʊ/ 앞에서는 ㅅ, 그 밖의 모음 앞에서는 ㅆ, 다른 자음 앞에서는 ㅅ, 종성에서는 ᆺ. 네 형태는 하나의 음소 /s/에 속한다(제5조의2 ②). /uː, ʊ/ 경계는 시범규칙이며 대조시험 대상이다(제5조의2 ③).",
    example: "sun 썬 · soon 수운 · soot 숱 · spin ㅅᄑᆝᆫ · pass 팻",
  },
  {
    id: "EN-P-016", jv: "JV-EN-016",
    ipa: "/z/", bare: "z",
    mode: "phonemic", canonical: "ᄶ",
    pos: {"초성": "ᄶ", "종성": "ퟯ"},
    rules: ["RV-EN-BASE-00"],
    slug: "EN-z", cls: "치경 마찰음", status: "종성 시험",
    context: "종성형은 시험 단계다.",
    example: "zoo ᄶᅮ우",
  },
  {
    id: "EN-P-017", jv: "JV-EN-017",
    ipa: "/ʃ/", bare: "ʃ",
    mode: "phonemic", canonical: "ᅀ",
    pos: {"초성": "ᅀ", "종성": "ᇫ"},
    rules: ["RV-EN-BASE-00"],
    slug: "EN-sh", cls: "후치경 마찰음", status: "확정",
    context: "",
    example: "shine ᅀᅡ인",
  },
  {
    id: "EN-P-018", jv: "JV-EN-018",
    ipa: "/ʒ/", bare: "ʒ",
    mode: "phonemic", canonical: "ᅆ",
    pos: {"초성": "ᅆ", "종성": "ᇲ"},
    rules: ["RV-EN-BASE-00"],
    slug: "EN-zh", cls: "후치경 마찰음", status: "종성 시험",
    context: "종성형은 시험 단계다.",
    example: "measure 메ᅆᆞ",
  },
  {
    id: "EN-P-019", jv: "JV-EN-019",
    ipa: "/h/", bare: "h",
    mode: "phonemic", canonical: "ᄒ",
    pos: {"초성": "ᄒ", "종성": "ᇂ"},
    rules: ["RV-EN-BASE-00"],
    slug: "EN-h", cls: "성문 마찰음", status: "확정",
    context: "영어에서 종성으로 실현되지 않는다.",
    example: "happy 해피",
  },
  {
    id: "EN-P-020", jv: "JV-EN-020",
    ipa: "/tʃ/", bare: "tʃ",
    mode: "phonemic", canonical: "ᅉ",
    pos: {"초성": "ᅉ"},
    rules: ["RV-EN-BASE-00"],
    slug: "EN-tsh", cls: "후치경 파찰음", status: "종성 미정",
    context: "종성 부호열은 미정(제5조의2 ⑥).",
    example: "chicken ᅉᆝᆿᄏᆝᆫ",
  },
  {
    id: "EN-P-021", jv: "JV-EN-021",
    ipa: "/dʒ/", bare: "dʒ",
    mode: "phonemic", canonical: "ᅈ",
    pos: {"초성": "ᅈ"},
    rules: ["RV-EN-BASE-00"],
    slug: "EN-dzh", cls: "후치경 파찰음", status: "종성 미정",
    context: "종성 부호열은 등록부에서 별도 확정한다.",
    example: "judge",
  },
  {
    id: "EN-P-022", jv: "JV-EN-022",
    ipa: "/l/", bare: "l",
    mode: "phonemic", canonical: "ᄅ",
    pos: {"초성": "ᄅ", "종성": "ᆯ"},
    rules: ["RV-EN-BASE-00"],
    slug: "EN-l", cls: "치경 설측 접근음", status: "확정",
    context: "clear L을 기본값으로 한다. dark L은 음성 모드의 별도 항목이다.",
    example: "love",
  },
  {
    id: "EN-P-023", jv: "JV-EN-023",
    ipa: "/ɹ/", bare: "ɹ",
    mode: "phonemic", canonical: "ꥶ",
    pos: {"초성": "ꥶ", "종성": "ퟛ"},
    rules: ["RV-EN-BASE-00"],
    slug: "EN-r", cls: "치경 접근음", status: "확정",
    context: "초성과 종성의 부호열이 다르며 하나의 자모값 ID로 묶인다(제5조의2 ①).",
    example: "rub ꥶᅥᆸ · far ᅋᅡퟛ",
  },
  {
    id: "EN-P-024", jv: "JV-EN-024",
    ipa: "/j/", bare: "j",
    mode: "phonemic", canonical: "ᅙ",
    pos: {"초성": "ᅙ"},
    rules: ["RV-EN-BASE-00"],
    slug: "EN-j", cls: "경구개 접근음", status: "확정",
    context: "",
    example: "young ᅙᅥᆼ",
  },
  {
    id: "EN-P-025", jv: "JV-EN-025",
    ipa: "[p]", bare: "p",
    mode: "phonetic", canonical: "ᄈ",
    pos: {"초성": "ᄈ"},
    rules: ["RV-EN-BASE-00"],
    slug: "EN-p_unasp", cls: "무기 파열음", status: "음성 모드",
    context: "/s/ 뒤에서만 쓴다. 음소 모드의 기본값을 대체하지 않는다.",
    example: "spin ㅅᄈᆝᆫ",
  },
  {
    id: "EN-P-026", jv: "JV-EN-026",
    ipa: "[t]", bare: "t",
    mode: "phonetic", canonical: "ᄄ",
    pos: {"초성": "ᄄ"},
    rules: ["RV-EN-BASE-00"],
    slug: "EN-t_unasp", cls: "무기 파열음", status: "음성 모드",
    context: "/s/ 뒤에서만 쓴다.",
    example: "stool ㅅ뚜울",
  },
  {
    id: "EN-P-027", jv: "JV-EN-027",
    ipa: "[k]", bare: "k",
    mode: "phonetic", canonical: "ᄁ",
    pos: {"초성": "ᄁ"},
    rules: ["RV-EN-BASE-00"],
    slug: "EN-k_unasp", cls: "무기 파열음", status: "음성 모드",
    context: "/s/ 뒤에서만 쓴다.",
    example: "skill ㅅᄁᆝᆯ",
  },
  {
    id: "EN-P-028", jv: "JV-EN-028",
    ipa: "[n̩]", bare: "n̩",
    mode: "phonetic", canonical: "ᆫ",
    pos: {"종성": "ᆫ"},
    rules: ["RV-EN-BASE-00"],
    slug: "EN-n_syl", cls: "음절 자음", status: "음성 모드",
    context: "분절 자모와 자음성 속성을 함께 저장한다.",
    example: "button",
  },
  {
    id: "EN-P-029", jv: "JV-EN-029",
    ipa: "[ɾ]", bare: "ɾ",
    mode: "phonetic", canonical: "ᄅ",
    pos: {"초성": "ᄅ"},
    rules: ["RV-EN-BASE-00"],
    slug: "EN-flap", cls: "탄설음", status: "음성 모드",
    context: "미국식 모음 사이 /t/의 음성 모드 실현.",
    example: "water",
  },
  {
    id: "EN-P-030", jv: "JV-EN-030",
    ipa: "[ɫ]", bare: "ɫ",
    mode: "phonetic", canonical: "ᇐ",
    pos: {"종성": "ᇐ"},
    rules: ["RV-EN-BASE-00"],
    slug: "EN-dark_l", cls: "연구개화 설측음", status: "음성 모드",
    context: "음성 모드에서만 쓴다.",
    example: "tell",
  },
  {
    id: "EN-P-031", jv: "JV-EN-031",
    ipa: "[ʔ]", bare: "ʔ",
    mode: "phonetic", canonical: "",
    pos: {},
    rules: ["RV-EN-BASE-00"],
    slug: "EN-glottal", cls: "성문 파열음", status: "미정",
    context: "역사적 ㆆ 사례는 참고하되 현대 기본값은 시험 전까지 비운다.",
    example: "",
  },
  {
    id: "EN-P-032", jv: "JV-EN-032",
    ipa: "/iː/", bare: "iː",
    mode: "phonemic", canonical: "ᅵ이",
    pos: {"중성": "ᅵ이"},
    rules: ["RV-EN-BASE-00"],
    slug: "EN-i_long", cls: "고전설 비원순 장모음", status: "확정",
    context: "장음은 중성을 겹쳐 적는다(제5조의2 관련 없음, 제1부 9절 (9)).",
    example: "seat 씨잍",
  },
  {
    id: "EN-P-033", jv: "JV-EN-033",
    ipa: "/ɪ/", bare: "ɪ",
    mode: "phonemic", canonical: "ᆝ",
    pos: {"중성": "ᆝ"},
    rules: ["RV-EN-BASE-00"],
    slug: "EN-ih", cls: "근고 전설 비원순", status: "확정",
    context: "/iː/와 구별한다.",
    example: "sit ᄊᆝᇀ",
  },
  {
    id: "EN-P-034", jv: "JV-EN-034",
    ipa: "/ɛ/", bare: "ɛ",
    mode: "phonemic", canonical: "ᅦ",
    pos: {"중성": "ᅦ"},
    rules: ["RV-EN-BASE-00"],
    slug: "EN-e", cls: "중저 전설 비원순", status: "확정",
    context: "",
    example: "pet 펱",
  },
  {
    id: "EN-P-035", jv: "JV-EN-035",
    ipa: "/æ/", bare: "æ",
    mode: "phonemic", canonical: "ᅢ",
    pos: {"중성": "ᅢ"},
    rules: ["RV-EN-BASE-00"],
    slug: "EN-ae", cls: "근저 전설 비원순", status: "확정",
    context: "",
    example: "pat 팻",
  },
  {
    id: "EN-P-036", jv: "JV-EN-036",
    ipa: "/ə/", bare: "ə",
    mode: "phonemic", canonical: "ᆞ",
    pos: {"중성": "ᆞ"},
    rules: ["RV-EN-BASE-00"],
    slug: "EN-schwa", cls: "중설 약모음", status: "확정",
    context: "",
    example: "control",
  },
  {
    id: "EN-P-037", jv: "JV-EN-037",
    ipa: "/ʌ/", bare: "ʌ",
    mode: "phonemic", canonical: "ᅥ",
    pos: {"중성": "ᅥ"},
    rules: ["RV-EN-BASE-00"],
    slug: "EN-uh", cls: "중저 후설 비원순", status: "시범값",
    context: "시범값이다.",
    example: "sun 썬",
  },
  {
    id: "EN-P-038", jv: "JV-EN-038",
    ipa: "/ɜː/", bare: "ɜː",
    mode: "phonemic", canonical: "ᅥ어",
    pos: {"중성": "ᅥ어"},
    rules: ["RV-EN-BASE-00"],
    slug: "EN-er_long", cls: "장 중설 모음", status: "시범값",
    context: "RP 시범형이다.",
    example: "bird",
  },
  {
    id: "EN-P-039", jv: "JV-EN-039",
    ipa: "/ʊ/", bare: "ʊ",
    mode: "phonemic", canonical: "ᅮ",
    pos: {"중성": "ᅮ"},
    rules: ["RV-EN-BASE-00"],
    slug: "EN-u", cls: "근고 후설 원순", status: "확정",
    context: "앞선 /s/를 ㅅ 위치형으로 유발한다.",
    example: "foot · soot 숱",
  },
  {
    id: "EN-P-040", jv: "JV-EN-040",
    ipa: "/uː/", bare: "uː",
    mode: "phonemic", canonical: "ᅮ우",
    pos: {"중성": "ᅮ우"},
    rules: ["RV-EN-BASE-00"],
    slug: "EN-u_long", cls: "고 후설 원순 장모음", status: "확정",
    context: "앞선 /s/를 ㅅ 위치형으로 유발한다.",
    example: "soon 수운",
  },
  {
    id: "EN-P-041", jv: "JV-EN-041",
    ipa: "/ɒ/", bare: "ɒ",
    mode: "phonemic", canonical: "ᅩ",
    pos: {"중성": "ᅩ"},
    rules: ["RV-EN-BASE-00"],
    slug: "EN-o_open", cls: "저후설 원순", status: "확정",
    context: "RP 모듈.",
    example: "hot 홑",
  },
  {
    id: "EN-P-042", jv: "JV-EN-042",
    ipa: "/ɔː/", bare: "ɔː",
    mode: "phonemic", canonical: "ᅩ오",
    pos: {"중성": "ᅩ오"},
    rules: ["RV-EN-BASE-00"],
    slug: "EN-o_long", cls: "장 원순모음", status: "대조시험 대상",
    context: "RP 모듈. 앞선 /s/의 위치형은 대조시험 대상이다(제5조의2 ③).",
    example: "saw 쏘오 · sought 쏘옽",
  },
  {
    id: "EN-P-043", jv: "JV-EN-043",
    ipa: "/ɔ/", bare: "ɔ",
    mode: "phonemic", canonical: "ᆂ",
    pos: {"중성": "ᆂ"},
    rules: ["RV-EN-BASE-00"],
    slug: "EN-o_ga", cls: "GA 중성 시범값", status: "시범값",
    context: "GA 모듈.",
    example: "dog ᄃᆂᆨ",
  },
  {
    id: "EN-P-044", jv: "JV-EN-044",
    ipa: "/ɑ/", bare: "ɑ",
    mode: "phonemic", canonical: "ᅡ",
    pos: {"중성": "ᅡ"},
    rules: ["RV-EN-BASE-00"],
    slug: "EN-a", cls: "저후설 비원순", status: "확정",
    context: "GA 모듈.",
    example: "hot 핱",
  },
  {
    id: "EN-P-045", jv: "JV-EN-045",
    ipa: "/ɑː/", bare: "ɑː",
    mode: "phonemic", canonical: "ᅡ아",
    pos: {"중성": "ᅡ아"},
    rules: ["RV-EN-BASE-00"],
    slug: "EN-a_long", cls: "장 저후설 비원순", status: "확정",
    context: "RP 모듈.",
    example: "park 파앜",
  },
  {
    id: "EN-P-046", jv: "JV-EN-046",
    ipa: "/eɪ/", bare: "eɪ",
    mode: "phonemic", canonical: "ᅦ이",
    pos: {"중성": "ᅦ이"},
    rules: ["RV-EN-BASE-00"],
    slug: "EN-ei", cls: "복모음", status: "확정",
    context: "단일 자모값으로 본다(지정 결합).",
    example: "say 쎄이",
  },
  {
    id: "EN-P-047", jv: "JV-EN-047",
    ipa: "/aɪ/", bare: "aɪ",
    mode: "phonemic", canonical: "ᅡ이",
    pos: {"중성": "ᅡ이"},
    rules: ["RV-EN-BASE-00"],
    slug: "EN-ai", cls: "복모음", status: "확정",
    context: "단일 자모값으로 본다(지정 결합).",
    example: "bite 바잍",
  },
  {
    id: "EN-P-048", jv: "JV-EN-048",
    ipa: "/ɔɪ/", bare: "ɔɪ",
    mode: "phonemic", canonical: "ᅩ이",
    pos: {"중성": "ᅩ이"},
    rules: ["RV-EN-BASE-00"],
    slug: "EN-oi", cls: "복모음", status: "확정",
    context: "단일 자모값으로 본다(지정 결합).",
    example: "boy 보이",
  },
  {
    id: "EN-P-049", jv: "JV-EN-049",
    ipa: "/aʊ/", bare: "aʊ",
    mode: "phonemic", canonical: "ᅡ우",
    pos: {"중성": "ᅡ우"},
    rules: ["RV-EN-BASE-00"],
    slug: "EN-au", cls: "복모음", status: "확정",
    context: "단일 자모값으로 본다(지정 결합).",
    example: "how 하우",
  },
  {
    id: "EN-P-050", jv: "JV-EN-050",
    ipa: "/oʊ/", bare: "oʊ",
    mode: "phonemic", canonical: "ᅩ우",
    pos: {"중성": "ᅩ우"},
    rules: ["RV-EN-BASE-00"],
    slug: "EN-ou", cls: "복모음", status: "확정",
    context: "지역 모듈에 따라 /əʊ/에도 대응한다.",
    example: "low 로우",
  },
  {
    id: "EN-P-051", jv: "JV-EN-051",
    ipa: "/ɪə/", bare: "ɪə",
    mode: "phonemic", canonical: "ᆝᄋᆞ",
    pos: {"중성": "ᆝᄋᆞ"},
    rules: ["RV-EN-BASE-00"],
    slug: "EN-ie", cls: "중심화 복모음", status: "시범값",
    context: "RP 시범형.",
    example: "near",
  },
  {
    id: "EN-P-052", jv: "JV-EN-052",
    ipa: "/ʊə/", bare: "ʊə",
    mode: "phonemic", canonical: "ᅮᄋᆞ",
    pos: {"중성": "ᅮᄋᆞ"},
    rules: ["RV-EN-BASE-00"],
    slug: "EN-ue", cls: "중심화 복모음", status: "시범값",
    context: "RP 시범형.",
    example: "pure",
  },
];

/** bare IPA → 항목. 음소(/x/)와 이음([x])이 같은 글자를 쓰므로 모드로 가른다. */
export const BY_IPA = new Map();
for (const e of ENTRIES) {
  const key = e.mode === 'phonetic' ? '[' + e.bare + ']' : e.bare;
  BY_IPA.set(key, e);
}

export const PHONEMIC = ENTRIES.filter((e) => e.mode === "phonemic");
export const PHONETIC = ENTRIES.filter((e) => e.mode === "phonetic");
